baseURL = 'https://robloxapi.github.io/ref/'
languageCode = 'en-us'
title = 'Roblox API Reference'
uglyURLs = true
disablePathToLower = true

markup.goldmark.renderer.unsafe = true

[params]
debug = false
theme = "auto"
repo = "https://github.com/robloxapi/roar"
issues = "https://github.com/robloxapi/roar/issues"
roblox = "https://www.roblox.com"
creatorhub = "https://create.roblox.com/docs/en-us/reference/engine"
license = "https://creativecommons.org/licenses/by-sa/4.0/"
author = "https://anaminus.github.io"
